# Generated by Django 3.2 on 2022-02-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(max_length=255)),
                ('distance', models.FloatField(max_length=255)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
