# Generated by Django 3.2 on 2022-02-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabledata',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
